
export const DashboardData: Array<any> = [
        {
            decisionReached: 'Yes',
            topic: 'Confirmation of resource availability',
            programCode: 'C509a (#1017 & #1018)',
            category: 'Anti-Infectives',
            timingCriticality: '7/9/2024',
            dm: 'Yes',
            sdsaStats: 'No',
            clinicalOps: 'Yes',
            clinPharm: 'No',
            regulatory: 'Yes',
            oarsGsso: 'Yes',
            pharmSciGcs: 'Yes',
            ded: 'No',
            mw: 'No'
        },
        {
            decisionReached: 'No',
            topic: 'Confirmation of resource availability 1',
            programCode: 'C5010a (#1020 & #1021)',
            category: 'Internal Medicine',
            timingCriticality: '8/24/2024',
            dm: 'Yes',
            sdsaStats: 'No',
            clinicalOps: 'No',
            clinPharm: 'Yes',
            regulatory: 'Yes',
            oarsGsso: 'Yes',
            pharmSciGcs: 'No',
            ded: 'Yes',
            mw: 'Yes'
        },
        {
            decisionReached: 'No',
            topic: 'Confirmation of resource availability',
            programCode: 'C5011a (#1021 & #1022)',
            category: 'Internal Medicine',
            timingCriticality: '4/22/2024',
            dm: 'No',
            sdsaStats: 'Yes',
            clinicalOps: 'No',
            clinPharm: 'Yes',
            regulatory: 'Yes',
            oarsGsso: 'No',
            pharmSciGcs: 'No',
            ded: 'No',
            mw: 'No'
        },
        {
            decisionReached: 'No',
            topic: 'Confirmation of resource availability',
            programCode: 'C5012a (#1022 & #1023)',
            category: 'Oncology',
            timingCriticality: '5/23/2024',
            dm: 'No',
            sdsaStats: 'No',
            clinicalOps: 'Yes',
            clinPharm: 'Yes',
            regulatory: 'No',
            oarsGsso: 'No',
            pharmSciGcs: 'No',
            ded: 'No',
            mw: 'Yes'
        },
        {
            decisionReached: 'No',
            topic: 'Confirmation of resource availability',
            programCode: 'C5013a (#1023 & #1024)',
            category: 'Vaccines',
            timingCriticality: '9/23/2024',
            dm: 'No',
            sdsaStats: 'Yes',
            clinicalOps: 'Yes',
            clinPharm: 'Yes',
            regulatory: 'Yes',
            oarsGsso: 'Yes',
            pharmSciGcs: 'Yes',
            ded: 'No',
            mw: 'Yes'
        },
        {
            decisionReached: 'No',
            topic: 'Confirmation of resource availability',
            programCode: 'C5014a (#1024 & #1025)',
            category: 'Anti-Infectives',
            timingCriticality: '3/25/2024',
            dm: 'No',
            sdsaStats: 'No',
            clinicalOps: 'Yes',
            clinPharm: 'No',
            regulatory: 'Yes',
            oarsGsso: 'Yes',
            pharmSciGcs: 'No',
            ded: 'No',
            mw: 'No'
        },
        {
            decisionReached: 'Yes',
            topic: 'Confirmation of resource availability',
            programCode: 'C5015a (#1025 & #1026)',
            category: 'Internal Medicine',
            timingCriticality: '6/17/2024',
            dm: 'Yes',
            sdsaStats: 'No',
            clinicalOps: 'Yes',
            clinPharm: 'No',
            regulatory: 'Yes',
            oarsGsso: 'No',
            pharmSciGcs: 'Yes',
            ded: 'No',
            mw: 'No'
        },
        {
            decisionReached: 'Yes',
            topic: 'Confirmation of resource availability',
            programCode: 'C5016a (#1026 & #1027)',
            category: 'Internal Medicine',
            timingCriticality: '11/19/2024',
            dm: 'Yes',
            sdsaStats: 'Yes',
            clinicalOps: 'Yes',
            clinPharm: 'Yes',
            regulatory: 'No',
            oarsGsso: 'No',
            pharmSciGcs: 'No',
            ded: 'No',
            mw: 'Yes'
        },
        {
            decisionReached: 'No',
            topic: 'Confirmation of resource availability',
            programCode: 'C5017a (#1027 & #1028)',
            category: 'Oncology',
            timingCriticality: '11/25/2024',
            dm: 'Yes',
            sdsaStats: 'Yes',
            clinicalOps: 'No',
            clinPharm: 'No',
            regulatory: 'No',
            oarsGsso: 'No',
            pharmSciGcs: 'Yes',
            ded: 'Yes',
            mw: 'No'
        },
        {
            decisionReached: 'No',
            topic: 'Confirmation of resource availability',
            programCode: 'C5018a (#1028 & #1029)',
            category: 'Internal Medicine',
            timingCriticality: '4/28/2024',
            dm: 'No',
            sdsaStats: 'No',
            clinicalOps: 'Yes',
            clinPharm: 'Yes',
            regulatory: 'Yes',
            oarsGsso: 'No',
            pharmSciGcs: 'No',
            ded: 'Yes',
            mw: 'No'
        }
    ];
    

    export const TabularData: Array<any> =  [
        {
          status: 'Ongoing',
          dateLogged: '03-Aug-2024 16:10',
          plannedDiscussionDate: '10-Aug-2024',
          addedBy: 'Green,Peter',
          programCode: '12345',
          category: 'Category A',
          topic: 'Topic A',
          overview: 'Overview A',
          timingCriticality: 'High',
          sdsaStats: 'Stats A',
          sdsaStatsResources: 'Yes',
          clinicalOps: 'Ops A',
          clinicalResources: 'Yes',
          clinPharm: 'Pharm A',
          clinPharmResources: 'Yes',
          regulatory: 'Reg A',
          regResources: 'Yes',
          oarsGsso: 'OARS A',
          oarsResources: 'Yes',
          pharmSciGcs: 'Sci A',
          pharmSciResources: 'Yes',
          ded: 'D&ED A',
          dedResources: 'Yes',
          mw: 'MW A',
          mwResources: 'Yes',
          downgrade: 'Downgrade A',
          risks: 'Risk A'
        },
        {
          status: 'Complete',
          dateLogged: '03-Aug-2024 16:08',
          plannedDiscussionDate: '10-Aug-2024',
          addedBy: 'Green,Peter',
          programCode: '12346',
          category: 'Category B',
          topic: 'Topic B',
          overview: 'Overview B',
          timingCriticality: 'Medium',
          sdsaStats: 'Stats B',
          sdsaStatsResources: 'No',
          clinicalOps: 'Ops B',
          clinicalResources: 'No',
          clinPharm: 'Pharm B',
          clinPharmResources: 'No',
          regulatory: 'Reg B',
          regResources: 'No',
          oarsGsso: 'OARS B',
          oarsResources: 'No',
          pharmSciGcs: 'Sci B',
          pharmSciResources: 'No',
          ded: 'D&ED B',
          dedResources: 'No',
          mw: 'MW B',
          mwResources: 'No',
          downgrade: 'Downgrade B',
          risks: 'Risk B'
        },
        {
          status: 'Critical',
          dateLogged: '03-Aug-2024 16:06',
          plannedDiscussionDate: '10-Aug-2024',
          addedBy: 'Green,Peter',
          programCode: '12347',
          category: 'Category C',
          topic: 'Topic C',
          overview: 'Overview C',
          timingCriticality: 'Low',
          sdsaStats: 'Stats C',
          sdsaStatsResources: 'Yes',
          clinicalOps: 'Ops C',
          clinicalResources: 'Yes',
          clinPharm: 'Pharm C',
          clinPharmResources: 'Yes',
          regulatory: 'Reg C',
          regResources: 'Yes',
          oarsGsso: 'OARS C',
          oarsResources: 'Yes',
          pharmSciGcs: 'Sci C',
          pharmSciResources: 'Yes',
          ded: 'D&ED C',
          dedResources: 'Yes',
          mw: 'MW C',
          mwResources: 'Yes',
          downgrade: 'Downgrade C',
          risks: 'Risk C'
        },
        {
          status: 'Ongoing',
          dateLogged: '30-Jul-2024 08:41',
          plannedDiscussionDate: '10-Aug-2024',
          addedBy: 'Green,Peter',
          programCode: '12348',
          category: 'Category D',
          topic: 'Topic D',
          overview: 'Overview D',
          timingCriticality: 'High',
          sdsaStats: 'Stats D',
          sdsaStatsResources: 'No',
          clinicalOps: 'Ops D',
          clinicalResources: 'No',
          clinPharm: 'Pharm D',
          clinPharmResources: 'No',
          regulatory: 'Reg D',
          regResources: 'No',
          oarsGsso: 'OARS D',
          oarsResources: 'No',
          pharmSciGcs: 'Sci D',
          pharmSciResources: 'No',
          ded: 'D&ED D',
          dedResources: 'No',
          mw: 'MW D',
          mwResources: 'No',
          downgrade: 'Downgrade D',
          risks: 'Risk D'
        },
        {
          status: 'Complete',
          dateLogged: '30-Jul-2024 08:33',
          plannedDiscussionDate: '10-Aug-2024',
          addedBy: 'Green,Peter',
          programCode: '12349',
          category: 'Category E',
          topic: 'Topic E',
          overview: 'Overview E',
          timingCriticality: 'Medium',
          sdsaStats: 'Stats E',
          sdsaStatsResources: 'Yes',
          clinicalOps: 'Ops E',
          clinicalResources: 'Yes',
          clinPharm: 'Pharm E',
          clinPharmResources: 'Yes',
          regulatory: 'Reg E',
          regResources: 'Yes',
          oarsGsso: 'OARS E',
          oarsResources: 'Yes',
          pharmSciGcs: 'Sci E',
          pharmSciResources: 'Yes',
          ded: 'D&ED E',
          dedResources: 'Yes',
          mw: 'MW E',
          mwResources: 'Yes',
          downgrade: 'Downgrade E',
          risks: 'Risk E'
        }
      ];